# Generated by Django 5.1.3 on 2024-12-22 09:31

from django.db import migrations, models



def migrate_route_to_facility(apps, schema_editor):
    PatientConsultation = apps.get_model("facility", "PatientConsultation")

    PatientConsultation.objects.update(route_to_facility=models.Case(
        models.When(deprecated_route_to_facility=10, then=models.Value("outp")), # OUTPATIENT
        models.When(deprecated_route_to_facility=20, then=models.Value("hosp-trans")), # INTER_FACILITY_TRANSFER
        models.When(deprecated_route_to_facility=30, then=models.Value("hosp-trans")), # INTRA_FACILITY_TRANSFER
        default=models.Value("other"),
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0473_alter_facility_facility_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientconsultation',
            old_name='route_to_facility',
            new_name='deprecated_route_to_facility',
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='route_to_facility_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='route_to_facility',
            field=models.CharField(blank=True, choices=[('hosp-trans', 'Transferred from other hospital/location'), ('emd', 'From accident/emergency department'), ('outp', 'From outpatient department'), ('born', 'Born in hospital'), ('gp', 'General Practitioner referral'), ('mp', 'Medical Practitioner/physician referral'), ('nursing', 'From nursing home'), ('psych', 'From psychiatric hospital'), ('rehab', 'From rehabilitation facility'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.RunPython(migrate_route_to_facility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patientconsultation',
            name='route_to_facility',
            field=models.CharField(choices=[('hosp-trans', 'Transferred from other hospital/location'), ('emd', 'From accident/emergency department'), ('outp', 'From outpatient department'), ('born', 'Born in hospital'), ('gp', 'General Practitioner referral'), ('mp', 'Medical Practitioner/physician referral'), ('nursing', 'From nursing home'), ('psych', 'From psychiatric hospital'), ('rehab', 'From rehabilitation facility'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='deprecated_route_to_facility',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
